# Generated by Django 5.0.4 on 2024-05-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_listings_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imgURL',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
