# Generated by Django 5.0.4 on 2024-05-10 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
