# Generated by Django 5.0.4 on 2024-05-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_listing_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_user',
            new_name='owner',
        ),
    ]
