# Generated by Django 5.0.4 on 2024-05-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_price_listing_start_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='curr_bid',
            field=models.IntegerField(null=True),
        ),
    ]
