# Generated by Django 5.0.4 on 2024-05-10 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_curr_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchingUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
