# Generated by Django 5.0.4 on 2024-05-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_listing_bid_listing_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
