# Generated by Django 5.0.4 on 2024-05-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bids',
        ),
    ]
